#macro(INIT ROOT_DIR)
file(GLOB FILE_LIST LIST_DIRECTORIES true *)
foreach (FILE ${FILE_LIST})
    message(STATUS ${FILE})
endforeach ()

list(FILTER FILE_LIST INCLUDE REGEX ".+/build$")
list(LENGTH FILE_LIST BUILD_COUNT)
if (BUILD_COUNT GREATER 0)
    message(STATUS "prepare to remove all build files")
    list(GET FILE_LIST 0 TARGET_DIR)
        MESSAGE(STATUS ${TARGET_DIR})
    file(GLOB_RECURSE BUILD_FILES LIST_DIRECTORIES TRUE ${TARGET_DIR}/)
    foreach (F ${BUILD_FILES})
        MESSAGE(STATUS ${F})
    endforeach ()
#    file(REMOVE_RECURSE BUILD_FILES)
    message(STATUS "delete build files success")
else ()
    message(STATUS "create directory build/")
    file(MAKE_DIRECTORY ${PROJECT_SOURCE_DIR}/build)
    message(STATUS "build/ dir create success")
endif ()
#endmacro()